// Package report — types shared across the report package: data shapes consumed by the
// HTML template, the format writers, and the JSON/CSV/SARIF marshallers.
package report

import (
	"html/template"

	"github.com/0hardik1/kubesplaining/internal/models"
)

// Summary tallies findings by severity bucket, reused at the global, module, category, and hotspot levels.
type Summary struct {
	Total    int
	Critical int
	High     int
	Medium   int
	Low      int
	Info     int
}

// Hotspot is a generic "label + summary" entry used in the top-namespaces/subjects/resources sidebar lists.
type Hotspot struct {
	Label   string
	Summary Summary
}

// ModuleSection groups findings by the module that emitted them for per-module display in the HTML report.
// RuleGroups is the rendering view: findings are bucketed by RuleID so the template can render shared
// rule-level content (title, MITRE, References) once and list per-subject instances below.
// Findings is preserved for callers that want the flat list (TOC builders, snapshot exports).
type ModuleSection struct {
	ID         string // slug used as an anchor ID
	Label      string
	Summary    Summary
	Findings   []models.Finding
	RuleGroups []RuleGroup
	Entries    []TOCEntry // collapsed one-row-per-RuleID list for the Findings-tab TOC
}

// RuleGroup collapses all findings sharing a RuleID into a single rendering unit. Each group
// renders once as a "rule card" with shared educational content (rule title, MITRE techniques,
// References) at the top, and one collapsed <details> instance per affected subject below.
//
// TopSeverity is the highest severity across instances; MaxScore/MinScore bracket the score range.
// Anchor matches AnchorByID for the first instance — narrative chips and TOC rows already point
// here, so the rule card lands on existing deep-links without churn.
type RuleGroup struct {
	RuleID          string
	RuleTitle       string // subject-neutralized title for the rule header
	TopSeverity     models.Severity
	MaxScore        float64
	MinScore        float64
	InstanceCount   int
	Anchor          string
	MitreTechniques []models.MitreTechnique
	LearnMore       []models.Reference
	References      []string
	Findings        []models.Finding
}

// CategorySection groups findings by RiskCategory for the "By Attack Theme" panel; it does not carry the findings themselves.
// CSSKey is the short heatmap-style key (privesc | lateral | exfil | infra | evasion) used for filter matching.
type CategorySection struct {
	Key     string
	CSSKey  string
	Label   string
	Summary Summary
	Entries []TOCEntry // collapsed one-row-per-RuleID list for the Findings-tab TOC
}

// TOCEntry is one row in the Findings-tab table-of-contents — a single rule, the highest
// severity it fired at within its group, and the number of finding instances it produced.
// Anchor points at the deterministic per-rule anchor (id="finding-<RuleID>") that the
// first occurrence of each rule already carries on its <article> card.
type TOCEntry struct {
	RuleID   string
	Title    string
	Severity models.Severity
	Anchor   string
	Count    int
}

// NarrativeCard is an auto-detected attack chain — a short plain-English walkthrough of how specific
// findings compose into a real-world exploit path. Generated by the narrative detectors, not hand-authored per cluster.
type NarrativeCard struct {
	Title    string
	Severity string // CRITICAL / HIGH
	Steps    []NarrativeStep
	RuleIDs  []string
}

// NarrativeStep is one numbered step in a NarrativeCard. Items is optional; when non-empty
// the template renders a bulleted sublist under Text — used to surface long subject/resource
// lists (e.g. thousands of service accounts) without ballooning the card width.
type NarrativeStep struct {
	Text  string
	Items []string
}

// HeatmapCell is one cell of the Resource × Category heatmap. Level is 0..5 for CSS intensity class.
// Resource is duplicated on every cell to keep the template flat — clicking a cell needs both the
// row's resource and the column's category to set Findings-tab filter chips.
type HeatmapCell struct {
	Count    int
	CatClass string // privesc | lateral | exfil | infra | evasion
	Level    int    // 0..5
	Resource string // resourceDisplay() of the row, copied for click-handler convenience
}

// HeatmapRow is one row of the Resource × Category heatmap.
type HeatmapRow struct {
	Label    string
	SevClass string // crit | high | med  — derived from the highest-severity finding on this resource
	SevLabel string // CRIT | HIGH | MED
	Total    int
	Cells    []HeatmapCell
}

// HeatmapCategory is a column header in the heatmap.
type HeatmapCategory struct {
	Key   string // privesc | lateral | exfil | infra | evasion
	Label string
}

// AttackGraph is the 3-column flow diagram shown at the top of the report: entry points → abused capability → impact.
// All coordinates are precomputed in Go so the template can emit SVG without any layout logic.
type AttackGraph struct {
	Width  int
	Height int
	Lanes  [3]GraphLane
	Nodes  []GraphNode
	Edges  []GraphEdge
	// Truncated reports whether the capability set was clipped to fit MaxCaps; the template
	// uses Shown / TotalCaps to render a notice above the diagram explaining the slate.
	Truncated bool
	Shown     int
	TotalCaps int
}

// GraphLane labels one of the three columns at the top of the attack graph.
// X is the lane's left edge (matches the X of nodes in that lane). LabelX/LabelW
// position the centered header pill — they are pre-computed so the template can
// emit `text-anchor=middle` and snug the pill width to its label.
type GraphLane struct {
	X      int
	Label  string
	LabelX int
	LabelW int
}

// GraphNode is a rendered rectangle in the attack graph. Kind is "entry" | "capability" | "impact".
// Text content lives in Lines so the template can emit pre-wrapped <text> elements without doing
// any layout work — Height is grown to match the wrapped line count. AriaLabel is the per-node
// accessible name announced by screen readers; without it every <g> would share a generic label
// like "Entry point" / "Abused capability" / "Impact" and be indistinguishable while tabbing.
type GraphNode struct {
	ID        string
	Kind      string
	X         int
	Y         int
	Width     int
	Height    int
	SevClass  string // crit | high | med
	AriaLabel string
	Lines     []GraphTextLine
}

// GraphTextLine is one rendered <text> baseline inside a node, positioned relative to the node origin.
type GraphTextLine struct {
	Class   string // CSS class: node-title | node-sub | node-meta | rule-id | impact-title
	Text    string
	OffsetX int
	OffsetY int
}

// GraphEdge is a rendered bezier path in the attack graph.
type GraphEdge struct {
	ID    string // stable ID of the form "edge-<fromNodeID>-<toNodeID>" — used by the JS layer.
	Class string // crit | high | med
	D     string
}

// GraphPayload is the parallel detail-only payload that the inline JSON block embeds for the
// JS interactivity layer. It is kept separate from AttackGraph (which stays cosmetic — only
// what the SVG template needs) so multi-paragraph educational HTML doesn't bloat per-element
// attributes.
type GraphPayload struct {
	Nodes      []GraphNodeDetail             `json:"Nodes"`
	Edges      []GraphEdgeDetail             `json:"Edges"`
	Glossary   map[string]GlossaryEntry      `json:"Glossary"`
	Techniques map[string]TechniqueExplainer `json:"Techniques"`
	Categories map[string]CategoryExplainer  `json:"Categories"`
}

// GraphNodeDetail is the per-node detail payload — title, severity, glossary key, rule
// description, remediation, references, hop chain, and the IDs of edges this node connects
// to. Wired up to the SVG <g data-node-id> elements client-side.
type GraphNodeDetail struct {
	ID           string    `json:"ID"`
	Kind         string    `json:"Kind"`     // entry | capability | impact
	Severity     string    `json:"Severity"` // crit | high | med
	Title        string    `json:"Title"`
	Subtitle     string    `json:"Subtitle,omitempty"`
	GlossaryKey  string    `json:"GlossaryKey,omitempty"`  // entry nodes
	RuleID       string    `json:"RuleID,omitempty"`       // capability nodes
	TechniqueKey string    `json:"TechniqueKey,omitempty"` // capability nodes
	Description  string    `json:"Description,omitempty"`  // capability nodes
	Remediation  string    `json:"Remediation,omitempty"`  // capability nodes
	References   []string  `json:"References,omitempty"`   // capability nodes
	Hops         []HopView `json:"Hops,omitempty"`         // privesc-PATH capability nodes
	EdgeIDs      []string  `json:"EdgeIDs,omitempty"`      // edges incident on this node
	EntryKind    string    `json:"EntryKind,omitempty"`    // Subject | Resource (entry filter)
	RiskCategory string    `json:"RiskCategory,omitempty"` // impact nodes
}

// GraphEdgeDetail describes one bezier edge for the JS layer.
type GraphEdgeDetail struct {
	ID           string `json:"ID"`
	From         string `json:"From"`
	To           string `json:"To"`
	Class        string `json:"Class"` // crit | high | med
	TechniqueKey string `json:"TechniqueKey,omitempty"`
	ActionLabel  string `json:"ActionLabel,omitempty"` // human-readable verb (e.g., "abuses", "leads to")
}

// HopView is one walkthrough step for a privesc-PATH finding — pre-rendered so the JS does
// no derivation. Step is 1-indexed for display.
type HopView struct {
	Step         int    `json:"Step"`
	From         string `json:"From"`
	To           string `json:"To"`
	Action       string `json:"Action"`
	TechniqueKey string `json:"TechniqueKey"`
	Permission   string `json:"Permission,omitempty"`
	Gains        string `json:"Gains,omitempty"`
}

// LeastPrivilegeSection feeds the "Least Privilege" HTML tab. It surfaces every finding
// whose RuleID is part of leastprivilege.TabRuleIDPrefixes: both the new audit-driven
// rules (UNUSED-*, WILDCARD-USED-PARTIAL-*) and the pre-existing static cleanup rules
// (STALE-*, OVERBROAD-*). Two summary tables sit above the per-subject cards so an
// operator can scan "what's unused" and "what verbs to drop" without expanding every
// card; the cards carry the full prose and remediation YAML for the picked target.
type LeastPrivilegeSection struct {
	Total                 int
	WindowStart           string // pre-formatted "YYYY-MM-DD", empty when no audit data
	WindowEnd             string
	WindowDays            int
	EventsProcessed       int
	NonSAUsernames        int // unique non-ServiceAccount callers in the window (humans, groups, system:node:*); surfaces an explicit "out of scope" note in the tab
	HasAuditData          bool
	UnusedResources       []LPUnusedResourceRow
	RoleVerbMap           []LPRoleVerbRow
	ClusterAdminInventory []LPClusterAdminRow // inventory of every subject bound to the built-in cluster-admin ClusterRole
	Groups                []LeastPrivilegeGroup
}

// LPClusterAdminRow is one subject directly bound to the built-in cluster-admin
// ClusterRole. The "Subjects bound to cluster-admin" table is an inventory view sitting
// alongside the actionable narrowing tables: operators get a single scannable list of
// every identity that holds full cluster control so they can decide which entries are
// legitimate (built-in system:* subjects, the break-glass group) and which need to be
// pared back. IsSystem drives a softer visual treatment for the rows that are expected.
type LPClusterAdminRow struct {
	Binding     string
	SubjectKind string
	SubjectNs   string
	SubjectName string
	IsSystem    bool
}

// LPUnusedResourceRow is a single row in the "Unused RBAC resources" summary table at the
// top of the Least Privilege tab. Built from findings whose RuleID describes a whole
// Role/Binding as unused or stale (UNUSED-ROLE, UNUSED-RULE, STALE-*, OVERBROAD-*).
// Resource holds the kind+name display string (e.g. "Role/cleanup-helper") so the table
// doesn't need a separate Kind column - "RBACRule" is not a real Kubernetes kind, just
// an internal label the rbac analyzer uses, and surfacing it confused operators.
//
// Action is the actionable "what should I delete?" answer rendered as HTML so the
// binding name can sit inside a <code> chip. The plain-English explanation lives on
// Why (still a string).
type LPUnusedResourceRow struct {
	RuleID    string
	Severity  models.Severity
	Resource  string // "<Kind>/<name>" e.g. "ClusterRole/cluster-admin"
	Subject   string // compact "ns/name" or "name"
	Action    template.HTML
	Why       string
	FindingID string // anchor target for "jump to detail"
}

// LPRoleVerbRow is a single row in the "Role -> unused verbs" summary table. Built from
// findings whose RuleID describes verb-level narrowing opportunities (UNUSED-VERB,
// UNUSED-RULE with verb list, WILDCARD-USED-PARTIAL). UsedVerbs and UnusedVerbs are
// pre-rendered HTML (one entry per line, verbs/resources wrapped in <code>) so the
// template can drop them straight into the cells - showing both sides lets the operator
// sanity-check the narrowing recommendation against what the workload actually does.
// Action describes the concrete edit ("drop verbs X, Y" / "replace verbs: [*] with...")
// so the row is actionable without expanding the card.
type LPRoleVerbRow struct {
	RuleID      string
	Severity    models.Severity
	Role        string // "<Kind>/<name>" e.g. "Role/prod-deployer"
	Subject     string // compact "ns/name" or "name"
	UsedVerbs   template.HTML
	UnusedVerbs template.HTML
	Action      template.HTML
	FindingID   string
}

// LeastPrivilegeGroup is one (subject) bucket inside the Least Privilege tab. Cards
// are pre-sorted by severity then score so the worst opportunity surfaces first per
// subject.
type LeastPrivilegeGroup struct {
	SubjectLabel string // "ServiceAccount default/builder" or "Group system:masters"
	SubjectKind  string
	SubjectName  string
	SubjectNs    string
	Summary      Summary
	Cards        []LeastPrivilegeFindingCard
}

// LeastPrivilegeFindingCard wraps a single finding with extracted per-tab presentation
// data. SuggestedRoleYAML is pulled out of Evidence so the template can render it as a
// proper <pre><code> block instead of inline-code spans bleeding through markdown.
type LeastPrivilegeFindingCard struct {
	Finding           models.Finding
	SuggestedRoleYAML string
}

// ComplianceSection feeds the "Compliance Coverage" HTML tab. One ComplianceFrameworkView per
// registered framework, grouped by control. Rendered from compliance.Apply'd findings; if no
// findings carry the framework, the view is omitted from Frameworks. UnmappedCount is informational
// — how many findings in the report have no compliance mapping at all (e.g. internal-only rules).
type ComplianceSection struct {
	Total         int                       // findings with at least one framework tag
	UnmappedCount int                       // findings with zero framework tags
	Frameworks    []ComplianceFrameworkView // one per framework that has at least one control hit
}

// ComplianceFrameworkView is one framework's rollup — top-line counts plus the per-control rows.
type ComplianceFrameworkView struct {
	Slug      string
	Name      string
	ShortName string
	URL       string
	// CSSKey is a short kebab-case identifier ("cis" / "nsa") that the template uses to
	// switch framework-specific accent colors. Kept separate from Slug so the slug can
	// stay as the public API identifier ("CIS-1.9") even if we tweak CSS classes.
	CSSKey   string
	Summary  Summary                // severity tally across all findings tagged with this framework
	Controls []ComplianceControlRow // one row per (framework, control) pair, sorted by severity then count
}

// ComplianceControlRow is one control's rollup inside a framework view. Findings is the deduped
// list (no duplicate Finding.IDs) of every finding tagged with this control, sorted by severity
// then score for display.
type ComplianceControlRow struct {
	Control string
	Title   string
	URL     string
	// TopSeverity is the most-severe severity across the control's findings — drives the
	// left-stripe color on the control card. The Summary fields would let the template
	// re-derive this, but exposing it explicitly keeps the template free of nested
	// conditionals.
	TopSeverity models.Severity
	Summary     Summary
	Findings    []models.Finding
}

// htmlReportData is the template input for the HTML dashboard; assembled by BuildHTMLData.
type htmlReportData struct {
	Snapshot       models.Snapshot
	Recon          Recon
	Summary        Summary
	Findings       []models.Finding
	Modules        []ModuleSection
	Categories     []CategorySection
	TopNamespaces  []Hotspot
	TopSubjects    []Hotspot
	TopResources   []Hotspot
	TopFindings    []models.Finding
	LeastPrivilege LeastPrivilegeSection
	Compliance     ComplianceSection
	// DefaultTab is the data-active-tab attribute on <body> when the report loads.
	// Empty preserves the legacy default (attack). --least-privilege-only sets
	// "leastprivilege".
	DefaultTab string
	// LeastPrivilegeOnly is set when the CLI ran with --least-privilege-only. The
	// template uses it to hide the Attack Paths / Risk Overview / Findings tab
	// buttons and the recon panel, leaving only the Least Privilege tab visible.
	LeastPrivilegeOnly bool
	// UsageInfo carries the audit-log window summary rendered into the Least
	// Privilege tab header. nil when no --audit-log was supplied.
	UsageInfo *UsageInfo

	// Modern-dashboard fields — all derived from Findings so any cluster renders.
	RiskIndex   int
	RiskLevel   string        // LOW | MODERATE | HIGH | CRITICAL
	GaugeDash   string        // "arcLen gapLen" for stroke-dasharray (circumference = 2π·56 ≈ 351.86)
	GaugeColor  string        // hex for gauge stroke, severity-tinted
	Headline    string        // data-driven h1 ("2 independent paths to full cluster takeover", etc.)
	Summaries   template.HTML // short prose under the h1; pre-escaped by buildHeadline so template renders markup
	Narratives  []NarrativeCard
	HeatCats    []HeatmapCategory
	HeatRows    []HeatmapRow
	Graph       AttackGraph
	GraphJSON   template.JS       // JSON-marshaled GraphPayload, rendered into <script type="application/json">
	GraphScript template.JS       // Inline JS that powers the interactive graph (loaded from kpGraphScript const)
	AnchorByID  map[string]string // Finding.ID → "finding-<RuleID>" for the first finding of each rule

	// Admission carries the engine's admission-aware reweight summary. Empty Mode means
	// no admission-aware step ran; the template gates the banner on Mode.
	Admission models.AdmissionSummary

	// Truncation carries the --max-findings cap state. Truncated=false (the zero
	// value) means no cap was applied; the template gates the banner on
	// .Truncation.Truncated.
	Truncation models.TruncationInfo
}
