// Package report — types shared across the report package: data shapes consumed by the
// HTML template, the format writers, and the JSON/CSV/SARIF marshallers.
package report

import (
	"html/template"

	"github.com/0hardik1/kubesplaining/internal/models"
)

// Summary tallies findings by severity bucket, reused at the global, module, category, and hotspot levels.
type Summary struct {
	Total    int
	Critical int
	High     int
	Medium   int
	Low      int
	Info     int
}

// Hotspot is a generic "label + summary" entry used in the top-namespaces/subjects/resources sidebar lists.
type Hotspot struct {
	Label   string
	Summary Summary
}

// ModuleSection groups findings by the module that emitted them for per-module display in the HTML report.
// RuleGroups is the rendering view: findings are bucketed by RuleID so the template can render shared
// rule-level content (title, MITRE, References) once and list per-subject instances below.
// Findings is preserved for callers that want the flat list (TOC builders, snapshot exports).
type ModuleSection struct {
	ID         string // slug used as an anchor ID
	Label      string
	Summary    Summary
	Findings   []models.Finding
	RuleGroups []RuleGroup
	Entries    []TOCEntry // collapsed one-row-per-RuleID list for the Findings-tab TOC
}

// RuleGroup collapses all findings sharing a RuleID into a single rendering unit. Each group
// renders once as a "rule card" with shared educational content (rule title, MITRE techniques,
// References) at the top, and one collapsed <details> instance per affected subject below.
//
// TopSeverity is the highest severity across instances; MaxScore/MinScore bracket the score range.
// Anchor matches AnchorByID for the first instance — narrative chips and TOC rows already point
// here, so the rule card lands on existing deep-links without churn.
type RuleGroup struct {
	RuleID          string
	RuleTitle       string // subject-neutralized title for the rule header
	TopSeverity     models.Severity
	MaxScore        float64
	MinScore        float64
	InstanceCount   int
	Anchor          string
	MitreTechniques []models.MitreTechnique
	LearnMore       []models.Reference
	References      []string
	Findings        []models.Finding
}

// CategorySection groups findings by RiskCategory for the "By Attack Theme" panel; it does not carry the findings themselves.
// CSSKey is the short heatmap-style key (privesc | lateral | exfil | infra | evasion) used for filter matching.
type CategorySection struct {
	Key     string
	CSSKey  string
	Label   string
	Summary Summary
	Entries []TOCEntry // collapsed one-row-per-RuleID list for the Findings-tab TOC
}

// TOCEntry is one row in the Findings-tab table-of-contents — a single rule, the highest
// severity it fired at within its group, and the number of finding instances it produced.
// Anchor points at the deterministic per-rule anchor (id="finding-<RuleID>") that the
// first occurrence of each rule already carries on its <article> card.
type TOCEntry struct {
	RuleID   string
	Title    string
	Severity models.Severity
	Anchor   string
	Count    int
}

// NarrativeCard is an auto-detected attack chain — a short plain-English walkthrough of how specific
// findings compose into a real-world exploit path. Generated by the narrative detectors, not hand-authored per cluster.
type NarrativeCard struct {
	Title    string
	Severity string // CRITICAL / HIGH
	Steps    []NarrativeStep
	RuleIDs  []string
}

// NarrativeStep is one numbered step in a NarrativeCard. Items is optional; when non-empty
// the template renders a bulleted sublist under Text — used to surface long subject/resource
// lists (e.g. thousands of service accounts) without ballooning the card width.
type NarrativeStep struct {
	Text  string
	Items []string
}

// HeatmapCell is one cell of the Resource × Category heatmap. Level is 0..5 for CSS intensity class.
// Resource is duplicated on every cell to keep the template flat — clicking a cell needs both the
// row's resource and the column's category to set Findings-tab filter chips.
type HeatmapCell struct {
	Count    int
	CatClass string // privesc | lateral | exfil | infra | evasion
	Level    int    // 0..5
	Resource string // resourceDisplay() of the row, copied for click-handler convenience
}

// HeatmapRow is one row of the Resource × Category heatmap.
type HeatmapRow struct {
	Label    string
	SevClass string // crit | high | med  — derived from the highest-severity finding on this resource
	SevLabel string // CRIT | HIGH | MED
	Total    int
	Cells    []HeatmapCell
}

// HeatmapCategory is a column header in the heatmap.
type HeatmapCategory struct {
	Key   string // privesc | lateral | exfil | infra | evasion
	Label string
}

// AttackGraph is the 3-column flow diagram shown at the top of the report: entry points → abused capability → impact.
// All coordinates are precomputed in Go so the template can emit SVG without any layout logic.
type AttackGraph struct {
	Width  int
	Height int
	Lanes  [3]GraphLane
	Nodes  []GraphNode
	Edges  []GraphEdge
	// Truncated reports whether the capability set was clipped to fit MaxCaps; the template
	// uses Shown / TotalCaps to render a notice above the diagram explaining the slate.
	Truncated bool
	Shown     int
	TotalCaps int
}

// GraphLane labels one of the three columns at the top of the attack graph.
// X is the lane's left edge (matches the X of nodes in that lane). LabelX/LabelW
// position the centered header pill — they are pre-computed so the template can
// emit `text-anchor=middle` and snug the pill width to its label.
type GraphLane struct {
	X      int
	Label  string
	LabelX int
	LabelW int
}

// GraphNode is a rendered rectangle in the attack graph. Kind is "entry" | "capability" | "impact".
// Text content lives in Lines so the template can emit pre-wrapped <text> elements without doing
// any layout work — Height is grown to match the wrapped line count.
type GraphNode struct {
	ID       string
	Kind     string
	X        int
	Y        int
	Width    int
	Height   int
	SevClass string // crit | high | med
	Lines    []GraphTextLine
}

// GraphTextLine is one rendered <text> baseline inside a node, positioned relative to the node origin.
type GraphTextLine struct {
	Class   string // CSS class: node-title | node-sub | node-meta | rule-id | impact-title
	Text    string
	OffsetX int
	OffsetY int
}

// GraphEdge is a rendered bezier path in the attack graph.
type GraphEdge struct {
	ID    string // stable ID of the form "edge-<fromNodeID>-<toNodeID>" — used by the JS layer.
	Class string // crit | high | med
	D     string
}

// GraphPayload is the parallel detail-only payload that the inline JSON block embeds for the
// JS interactivity layer. It is kept separate from AttackGraph (which stays cosmetic — only
// what the SVG template needs) so multi-paragraph educational HTML doesn't bloat per-element
// attributes.
type GraphPayload struct {
	Nodes      []GraphNodeDetail             `json:"Nodes"`
	Edges      []GraphEdgeDetail             `json:"Edges"`
	Glossary   map[string]GlossaryEntry      `json:"Glossary"`
	Techniques map[string]TechniqueExplainer `json:"Techniques"`
	Categories map[string]CategoryExplainer  `json:"Categories"`
}

// GraphNodeDetail is the per-node detail payload — title, severity, glossary key, rule
// description, remediation, references, hop chain, and the IDs of edges this node connects
// to. Wired up to the SVG <g data-node-id> elements client-side.
type GraphNodeDetail struct {
	ID           string    `json:"ID"`
	Kind         string    `json:"Kind"`     // entry | capability | impact
	Severity     string    `json:"Severity"` // crit | high | med
	Title        string    `json:"Title"`
	Subtitle     string    `json:"Subtitle,omitempty"`
	GlossaryKey  string    `json:"GlossaryKey,omitempty"`  // entry nodes
	RuleID       string    `json:"RuleID,omitempty"`       // capability nodes
	TechniqueKey string    `json:"TechniqueKey,omitempty"` // capability nodes
	Description  string    `json:"Description,omitempty"`  // capability nodes
	Remediation  string    `json:"Remediation,omitempty"`  // capability nodes
	References   []string  `json:"References,omitempty"`   // capability nodes
	Hops         []HopView `json:"Hops,omitempty"`         // privesc-PATH capability nodes
	EdgeIDs      []string  `json:"EdgeIDs,omitempty"`      // edges incident on this node
	EntryKind    string    `json:"EntryKind,omitempty"`    // Subject | Resource (entry filter)
	RiskCategory string    `json:"RiskCategory,omitempty"` // impact nodes
}

// GraphEdgeDetail describes one bezier edge for the JS layer.
type GraphEdgeDetail struct {
	ID           string `json:"ID"`
	From         string `json:"From"`
	To           string `json:"To"`
	Class        string `json:"Class"` // crit | high | med
	TechniqueKey string `json:"TechniqueKey,omitempty"`
	ActionLabel  string `json:"ActionLabel,omitempty"` // human-readable verb (e.g., "abuses", "leads to")
}

// HopView is one walkthrough step for a privesc-PATH finding — pre-rendered so the JS does
// no derivation. Step is 1-indexed for display.
type HopView struct {
	Step         int    `json:"Step"`
	From         string `json:"From"`
	To           string `json:"To"`
	Action       string `json:"Action"`
	TechniqueKey string `json:"TechniqueKey"`
	Permission   string `json:"Permission,omitempty"`
	Gains        string `json:"Gains,omitempty"`
}

// htmlReportData is the template input for the HTML dashboard; assembled by BuildHTMLData.
type htmlReportData struct {
	Snapshot      models.Snapshot
	Summary       Summary
	Findings      []models.Finding
	Modules       []ModuleSection
	Categories    []CategorySection
	TopNamespaces []Hotspot
	TopSubjects   []Hotspot
	TopResources  []Hotspot
	TopFindings   []models.Finding

	// Modern-dashboard fields — all derived from Findings so any cluster renders.
	RiskIndex   int
	RiskLevel   string        // LOW | MODERATE | HIGH | CRITICAL
	GaugeDash   string        // "arcLen gapLen" for stroke-dasharray (circumference = 2π·56 ≈ 351.86)
	GaugeColor  string        // hex for gauge stroke, severity-tinted
	Headline    string        // data-driven h1 ("2 independent paths to full cluster takeover", etc.)
	Summaries   template.HTML // short prose under the h1; pre-escaped by buildHeadline so template renders markup
	Narratives  []NarrativeCard
	HeatCats    []HeatmapCategory
	HeatRows    []HeatmapRow
	Graph       AttackGraph
	GraphJSON   template.JS       // JSON-marshaled GraphPayload, rendered into <script type="application/json">
	GraphScript template.JS       // Inline JS that powers the interactive graph (loaded from kpGraphScript const)
	AnchorByID  map[string]string // Finding.ID → "finding-<RuleID>" for the first finding of each rule
}
